GET https://sidaya-api.onrender.com/api/supply/

###
GET https://sidaya-api.onrender.com

###
POST https://sidaya-api.onrender.com
Content-Type: application/json

{
    "name": "Pisang",
    "uom": "Buah"
}

###
PATCH http://localhost:4000/api/periode/9f1964bd-9045-4bf9-9f61-583a9fbbdfbd
Content-Type: application/json

{
    "name": "Hehehehaw"
}

###
DELETE http://localhost:4000/api/periode/9f1964bd-9045-4bf9-9f61-583a9fbbdfbd